name: underworld_game
description: "A new Flutter game project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flame: ^1.9.1 
  auto_route: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true


  assets:
    - assets/images/animations/
    - assets/images/
    - assets/sounds/